### PR TITLE
put all user content in the same message

### PR DESCRIPTION
**Pull request by nebilibrahim22**
# Description

This resolves an issue relating to messages argument in the sample notebook video_chatcompletions_example_restapi.ipynb. There is inconsistent behavior where if the document is not the first thing in the user message the response to the call might be something like "Sorry I cannot answer..." said question. Here there is a comment for clarification to let the user know to put the document ID first in the list. Also, there should be one user message. The content for both user messages is combined into one

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md)
- [x] I have coordinated with the docs team (mldocs@microsoft.com) if this PR deletes files or changes any file names or file extensions.
- [ x This notebook or file is added to the [CODEOWNERS](https://github.com/Azure-Samples/azureai-samples/blob/main/.github/CODEOWNERS) file, pointing to the author or the author's team.

### CODE REVIEW

**Comment by kdestin** [comment]
To address the CI failure, please consult the [Contributing Guidelines](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#2-install-dev-dependencies) to install the dev requirements and `pre-commit`. Then run `pre-commit run --all-files` from the root of the repository. 

This'll:

* Format the notebooks with black
* Remove unneeded metadata
* Surface some linting issues that need to be addressed.

**Comment by nebilibrahim22** [comment]
@kdestin  I fixed the changes so I think it is just pending approval from a repository owner

**Comment by kdestin** [comment]
@nebilibrahim22 You need to resolve the merge conflict

**Comment by nebilibrahim22** [comment]
@kdestin Sorry about that, should be all good now though

**Review by kdestin — APPROVED** [review]

**Pull request merged**
