### PR TITLE
Restructuring repo top-level directories

### PR DESCRIPTION
**Pull request by brandom-msft**
# Description

Renamed the existing "notebooks" to "scenarios", per feedback and phone call. 
Added a directory for incoming Assistants samples.
Minor update to the relevant section in CONTRIBUTING.md for adding new samples.

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md)
- [ ] I have coordinated with the docs team (mldocs@microsoft.com) if this PR deletes files or changes any file names or file extensions.
- [x] This notebook or file is added to the [CODEOWNERS](https://github.com/Azure-Samples/azureai-samples/blob/main/.github/CODEOWNERS) file, pointing to the author or the author's team.

### CODE REVIEW

**Comment by brandom-msft** [comment]
Current repo owners - are any of the existing samples tied to docs? I can coordinate with mldocs, if so.

**Review by trrwilson — APPROVED** [review]

**Comment by kdestin** [comment]
Was moving all the samples up a directory an one of the intended changes? My understanding was that the alignment proposal was for the structure under `notebooks/`.

The email mentioned a desire to have a similar structure to [openai/openai-cookbook](https://github.com/openai/openai-cookbook), which also nests the examples into a subdirectory of the root.

**Comment by kdestin** [comment]
> Current repo owners - are any of the existing samples tied to docs? I can coordinate with mldocs, if so.

I would reach out to mldocs to be sure.

**Comment by brandom-msft** [comment]
> Was moving all the samples into the repository root an intended change from the email thread? My understanding from the email and the initial meeting where the structure was flagged was that the alignment proposal was for the structure under `notebooks/`.
> 
> The email mentioned a desire to have a similar structure to [openai/openai-cookbook](https://github.com/openai/openai-cookbook), which also nests the samples into a subdirectory of the root.
> 
> If this change _was_ intended, I'd strongly advocate to keep the notebooks in a subdirectory.

@kdestin The overall theme was around growing this repo into _the_ main place for Azure AI sample offerings. And with that in mind, we want to enable exposure for samples in any language, be it Python, .NET, Java, <future>, etc.

The thinking behind the voted proposal was to put the scenario at the top level and then subdivide by format/language.


- GPT-V 
  - README
  - Scenario_1_notebook
  - Scenario_2_notebook
- Assistants
  - Assistants Readme
  - AsstScenario_1_notebook
- RAG
  - RAG Readme
  - Scenario_1_notebook
- <Scenario>
  - scenario README
  - Sample1
  - Sample2
  - Notebook1
- README

**Comment by kdestin** [comment]
@brandom-msft Definitely, I'm totally onboard with making the repo the main place for Azure AI sample offerings, and want changes to that end merged ASAP.

I have a couple concerns about the scenario folders to top level of the repository:
    * It might cause some confusion for customers if ever we need to add non-scenario folders to the root of the repository
    * Having all of the samples in one subdirectory makes some repository maintenance easier (low priority)

I'd definitely prefer if we could follow the voted on proposal under a subdirectory, but if that isn't possible no worries.

**Comment by brandom-msft** [comment]
> @brandom-msft Definitely, I'm totally onboard with making the repo the main place for Azure AI sample offerings, and want changes to that end merged ASAP.
> 
> I have a couple concerns about the scenario folders to top level of the repository:    * It might cause some confusion for customers if ever we need to add non-scenario folders to the root of the repository    * Having all of the samples in one subdirectory makes some repository maintenance easier (low priority)
> 
> I'd definitely prefer if we could follow the voted on proposal under a subdirectory (we could rename `notebooks/` to something language agnostic like `samples/`), but if that isn't possible no worries.
> 
> If we do end up moving the scenarios to top level, there are some templates (README + Jupyter Notebook) that no longer make sense to have in the `notebooks/` folder. Since `notebooks/` would otherwise be empty, consider renaming it to something like `.templates/`.

I hear you on wanting to reduce confusion should there be other non-scenario folders, but I'm wondering if that would be a misuse of this repo's purpose? (e.g. what else would go in `Azure-Samples/azureai-samples`?) 
I feel like that also becomes redundant to end up with `Azure-Samples/azureai-samples/samples`.

In any case, I'm not hard-line on these points. Let's have a brief meetup to sort it?

**Comment by brandom-msft** [comment]
@kdestin For Monday morning:
- looks like I can't self-approve, can you approve?
- (if I haven't solved this by then) the "checks" are showing a file conflict for `notebooks/GPT-4V/shared_functions.py`, but I can't resolve it nor do I see any conflicts. Any ideas?

**Review by kdestin — APPROVED** [review]

**Pull request merged**
